### ISSUE TITLE
swift 4 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [antonyraphel/ARCarMovement#1]
Hi I think your work is one of the best out here. I'd really appreciate it if you can do car movement like this one but in Swift 4

**Comment by antonyraphel** [comment]
Hi @AbdulazizAlmohsen 
This code is already updated with Swift 4.

**Comment by JaeeApp** [comment]
Can you help me with something please. In my iOS app I do http requests to get the driver coordinates every 30 seconds. How can implement your nice code to apply in my situation ? how to set old coordinate and update the new coordinates from my api ?

**Comment by antonyraphel** [comment]
Hey @JaeeApp 

**2 options:** 

1. Create one more column in your DB table for maintain old coordinate and when ever new update/API calls happen, in response pass those old and new coordinate.
2. Don't remove you car marker while updating with new position values. Create one **property** as _oldCoordinate_ and assign the new coordinate value once marker added/moved. When the api calls next time you have _oldCoordinate_ to make movement animation.

I hope this will work for you.
