### ISSUE TITLE
swift 4 or above version issue 

### ISSUE THREAD

**Issue by suryaween** [antonyraphel/ARCarMovement#14]
<img width="426" alt="Screenshot 2019-07-08 at 1 35 01 PM" src="https://user-images.githubusercontent.com/47106679/60793796-08fd0500-a186-11e9-950f-81f8918184de.png">

Hello whwnever i am trying to use this library it shows the same error can you please upgrade the code which supports swift 4.0 or above and xcode 10.2 or above 

Thanks

**Comment by antonyraphel** [comment]
#16
