### ISSUE TITLE
ARCarMovement-Swift.h' file not found

### ISSUE THREAD

**Issue by vijay1864** [antonyraphel/ARCarMovement#7]
iam working in objective c
and iam getting below error in .h file whenever import swift file
ARCarMovement-Swift.h' file not found

**Comment by antonyraphel** [comment]
Hi @vijay1864,

Please import like following,

` #import "<Your Defined Module Name>-Swift.h" `

for more details please refer [README.md](https://github.com/antonyraphel/ARCarMovement/blob/master/README.md)
